fix issuse #1446
airyland/vux pull request #1467
Opened 2017-05-24 04:17 UTC by xiaolongyuan

Please makes sure the items are checked before submitting your PR, thank you!

* [ ] `Rebase` before creating a PR to keep commit history clear.
* [ ] `Only One commit`
* [ ] No `eslint` errors

2017-05-24 05:46 UTC, airyland requested changes
注释的代码可以直接去掉，不在源码中保留，处理细节可以写在 pr 里说明。

2017-05-25 10:18 UTC, xiaolongyuan commented
好

2017-05-25 10:25 UTC, xiaolongyuan commented
修改了一下  去掉了注释 fix了之前逻辑的移除bug

2017-06-02 05:52 UTC, graysheeep commented
commits合并一下 然后在写个demo吧

2017-06-15 11:08 UTC, airyland commented
Vue.set 应该可以直接用 this.$set， 这样就不用 import Vue 了。

2017-07-19 07:48 UTC, Msms-NJ commented
正好需要这个功能，不知道什么时候正式版会发布这个功能

2017-07-30 08:52 UTC, merged