修改scroller组件，调用xscroll的destroy方法，从beforeDestroy换到destory
airyland/vux pull request #1973
Opened 2017-09-14 02:49 UTC by linhaobin

切换路由时，有动画过度时，如果是在beforeDestory调用xscroll的destory方法的话，在开始过度时滚动条会回到顶部，因为xscroll被destory了，如果在destory时再执行xscroll的destory方法就没有该问题。

* [x] `Rebase` before creating a PR to keep commit history clear.
* [x] `Only One commit`
* [x] No `eslint` errors

2017-09-14 03:21 UTC, airyland requested changes

2017-09-14 03:21 UTC, airyland commented on src/components/scroller/index.vue
> +  destroy () {
是 `destroyed` 吧

2017-09-14 03:21 UTC, airyland commented on src/components/scroller/metas.yml
> +      - '[change] call the xscroll destroy method, from frontDestroy to destroy
少了结束引号

2017-09-14 03:21 UTC, airyland commented on src/components/scroller/metas.yml
> +      - '[change] 调用xscroll的destroy方法，从beforeDestroy换到destory
少了结束引号

2017-09-14 10:08 UTC, linhaobin commented
@airyland 重新上传了

2017-09-14 11:33 UTC, airyland requested changes

2017-09-14 11:33 UTC, airyland commented on src/components/scroller/index.vue
> +  destoryed () {
destroyed

2017-09-14 11:33 UTC, airyland commented on src/components/scroller/metas.yml
> +      - '[change] call the xscroll destroy method, change beforeDestroy to destoryed'
destroyed

2017-09-14 11:33 UTC, airyland commented on src/components/scroller/metas.yml
> +      - '[change] 调用xscroll的destroy方法，从beforeDestroy换到destoryed'
destroyed

2017-09-15 02:21 UTC, linhaobin commented
嗯嗯，我写错了，把beforeDestroy改成destoryed，没有解决我的问题

2017-09-15 02:21 UTC, closed without merging

2017-09-23 08:40 UTC, luhf commented
本来我也是修改成destoryed，刚开始好使，后来更新版本又不行了，现在是把beforeDestroy中的this._xscroll.destroy()这句话注释掉好了。@airyland可以参考一下

2017-09-23 10:21 UTC, airyland commented
@luhf 不知道你说的更新版本不行是怎么个操作，这个组件已经 n 久不迭代了。