Dev vux form
airyland/vux pull request #3782
Opened 2021-07-10 08:18 UTC by eJayYoung

Please makes sure the items are checked before submitting your PR, thank you!

* [x] `Rebase` before creating a PR to keep commit history clear.
* [ ] `Only One commit`
* [x] No `eslint` errors

2021-07-11 12:29 UTC, caozhong1996 commented
这是个比较大的提交，我最近比较忙，需要一些时间review代码和验证功能，先给你点个赞👍👍

2021-07-12 07:09 UTC, eJayYoung commented
> 这是个比较大的提交，我最近比较忙，需要一些时间review代码和验证功能，先给你点个赞👍👍

不着急，慢慢review，我到时候还想把uploader也加上去

2021-07-18 11:11 UTC, caozhong1996 commented on src/demos/Form.vue
> +            type="number"
不用引入就能使用对应的组件看起来很好，但是仔细思考之后，这是建立在提前将 “可能” 需要的组件引入了，即
src/components/form/components.js文件下
`
import XInput from '../x-input'

import XTextarea from '../x-textarea'

import XNumber from '../x-number'

import Datetime from '../datetime'

import PopupPicker from '../popup-picker'

import PopupRadio from '../popup-radio'
`

假设用户在表单中只使用了 XInput 组件，那么其他组件的引入就没有必要（即使没有使用，也没办法treeshaking）。假设后续可能会有更多的组件需要在表单中验证，那么浪费的体积就会越来越多。所以我觉得还是让用户在表单中手动引入需要使用的组件比较好，不知道你的看法呢。

2021-07-18 11:18 UTC, caozhong1996 commented on src/components/form/form.vue
> +<style lang="less" scoped>
去掉这个scoped吧

2021-07-18 11:19 UTC, caozhong1996 commented on src/demos/Form.vue
> +            type="number"
不用引入就能使用对应的组件看起来很好，但是仔细思考之后，这是建立在提前将 “可能” 需要的组件引入了，即
src/components/form/components.js文件下
`
import XInput from '../x-input'

import XTextarea from '../x-textarea'

import XNumber from '../x-number'

import Datetime from '../datetime'

import PopupPicker from '../popup-picker'

import PopupRadio from '../popup-radio'
`

假设用户在表单中只使用了 XInput 组件，那么其他组件的引入就没有必要（即使没有使用，也没办法treeshaking）。假设后续可能会有更多的组件需要在表单中验证，那么浪费的体积就会越来越多。所以我觉得还是让用户在表单中手动引入需要使用的组件比较好，不知道你的看法呢。

2021-07-18 11:25 UTC, caozhong1996 commented on src/demos/Form.vue
> +<style lang="less">
`
@import '~vux/src/styles/reset.less';
html,
body {
  margin: 0;
  padding: 0;
  height: 100%;
}
#app {
  height: 100%;
`

这些demo的全局样式我觉得可以放在App.vue下

2021-07-18 11:28 UTC, caozhong1996 requested changes
总体上来看，基本实现了表单的功能，一些可能需要修改的地方我也标注出来了，我得认真一点review，不然也辜负你的付出。

2021-07-19 07:52 UTC, eJayYoung commented on src/demos/Form.vue
> +            type="number"
也可以，这是直接迁移我之前设计的第一版，要是从整个库打包的角度来说，当然是分开来好，那就把内置组件的概念去掉，只做Form&Field层，专注于表单数据的传递和获取以及校验就好，就类似element的form&field

2021-07-19 07:53 UTC, eJayYoung commented on src/components/form/form.vue
> +<style lang="less" scoped>
ok

2021-07-19 07:54 UTC, eJayYoung commented
> 总体上来看，基本实现了表单的功能，一些可能需要修改的地方我也标注出来了，我得认真一点review，不然也辜负你的付出。

辛苦了，提出的改动我会改好

2021-07-20 08:58 UTC, eJayYoung commented on src/demos/Form.vue
> +            type="number"
> 不用引入就能使用对应的组件看起来很好，但是仔细思考之后，这是建立在提前将 “可能” 需要的组件引入了，即
> src/components/form/components.js文件下
> `
> import XInput from '../x-input'
> 
> import XTextarea from '../x-textarea'
> 
> import XNumber from '../x-number'
> 
> import Datetime from '../datetime'
> 
> import PopupPicker from '../popup-picker'
> 
> import PopupRadio from '../popup-radio'
> `
> 
> 假设用户在表单中只使用了 XInput 组件，那么其他组件的引入就没有必要（即使没有使用，也没办法treeshaking）。假设后续可能会有更多的组件需要在表单中验证，那么浪费的体积就会越来越多。所以我觉得还是让用户在表单中手动引入需要使用的组件比较好，不知道你的看法呢。

有个疑问，为啥没办法treeshaking？

2021-07-21 02:16 UTC, caozhong1996 commented on src/demos/Form.vue
> +            type="number"
![image](https://user-images.githubusercontent.com/26522151/126419332-979c040d-a0e7-4b77-affb-af48a4c34433.png)
我认为是无法在构建阶段知道需要使用哪些组件的，那么只能全部打包进去了，其实在注册components的时候已经产生副作用了。
![image](https://user-images.githubusercontent.com/26522151/126419720-5a9e7724-18e6-415a-a5e7-322ab2728e92.png)
极端一点来说，这个component属性的值也有可能是通过网络请求获得的吧（动态的不能分析），打包的时候怎么确定需要哪些组件呢。不过你也可以打包试验一下看看，我也没有很详细的了解treeshaking。

2021-07-22 01:04 UTC, eJayYoung commented on src/demos/Form.vue
> +            type="number"
[tree-shaking](https://webpack.docschina.org/guides/tree-shaking/)是根据es6的`import`和`export`支持静态分析的特性，能够在运行时之前就把未引用的代码shake掉，不过这也不是重点。
我之前这样写，主要也是参考了[cube-ui](https://github.com/didi/cube-ui/blob/dev/src/components/form/form-item.vue)，方便以后用`schema`来渲染`form`，不过也可以先暂时按照slot插值的方式来写，由于还要改动一些demo用例，我这两天会晚些提交修改。

2021-07-22 01:05 UTC, eJayYoung commented
BTW：现在vux的demo都是vue版本都是2.5.x，是不是有空可以升级2.6.x，支持一下`v-slot`的写法 @caozhong1996

2021-07-22 01:29 UTC, caozhong1996 commented on src/demos/Form.vue
> +            type="number"
是的，确实有想到你期望 用schema来渲染form 这一点，只是我在想组件库的边界到底在哪里，之前vux-loader就是做了太多的事情，现在很难继续修改了，所以我偏向组件库做的事情应该少一点。

2021-07-22 01:32 UTC, caozhong1996 commented
> BTW：现在vux的demo都是vue版本都是2.5.x，是不是有空可以升级2.6.x，支持一下`v-slot`的写法 @caozhong1996

对了，你有兴趣参与vux的维护吗，可以向Airyland申请一下权限，我也有升级vue3的打算，但是还没想好怎么走比较合适，毕竟vue也很多成熟的移动端组件库了，vux应该有什么样的特色我还没想好。

2021-07-22 02:22 UTC, eJayYoung commented
> > BTW：现在vux的demo都是vue版本都是2.5.x，是不是有空可以升级2.6.x，支持一下`v-slot`的写法 @caozhong1996
> 
> 对了，你有兴趣参与vux的维护吗，可以向Airyland申请一下权限，我也有把vux升级vue3.0的打算，但是还没想好怎么走比较合适，毕竟vue也很多成熟的移动端组件库了，vux应该有什么样的特色我还没想好。

可以一起共建啊，我使用vux也差不多快三年了，于我而言，vux的核心可能就是weui风格的vue组件库了，因为很多移动端的组件库大同小异，都是一些细节处去争取差异化，vue3.0的升级break-change会比较多，可能需要类似[vue-next](https://github.com/vuejs/vue-next)，单独先领出来搞，而且现在vux的webpack也是3.x，我之前尝试过vue cli 3，还不错的，脚手架也需要升级

2021-07-23 07:05 UTC, caozhong1996 commented
> > > BTW：现在vux的demo都是vue版本都是2.5.x，是不是有空可以升级2.6.x，支持一下`v-slot`的写法 @caozhong1996
> > 
> > 
> > 对了，你有兴趣参与vux的维护吗，可以向Airyland申请一下权限，我也有把vux升级vue3.0的打算，但是还没想好怎么走比较合适，毕竟vue也很多成熟的移动端组件库了，vux应该有什么样的特色我还没想好。
> 
> 可以一起共建啊，我使用vux也差不多快三年了，于我而言，vux的核心可能就是weui风格的vue组件库了，因为很多移动端的组件库大同小异，都是一些细节处去争取差异化，vue3.0的升级break-change会比较多，可能需要类似[vue-next](https://github.com/vuejs/vue-next)，单独先领出来搞，而且现在vux的webpack也是3.x，我之前尝试过vue cli 3，还不错的，脚手架也需要升级

你可以发邮件让他帮你开权限  i@mao.li

2021-07-25 11:58 UTC, merged

2022-01-11 02:52 UTC, eJayYoung commented
> > > > BTW：现在vux的demo都是vue版本都是2.5.x，是不是有空可以升级2.6.x，支持一下`v-slot`的写法 @caozhong1996
> > > 
> > > 
> > > 对了，你有兴趣参与vux的维护吗，可以向Airyland申请一下权限，我也有把vux升级vue3.0的打算，但是还没想好怎么走比较合适，毕竟vue也很多成熟的移动端组件库了，vux应该有什么样的特色我还没想好。
> > 
> > 
> > 可以一起共建啊，我使用vux也差不多快三年了，于我而言，vux的核心可能就是weui风格的vue组件库了，因为很多移动端的组件库大同小异，都是一些细节处去争取差异化，vue3.0的升级break-change会比较多，可能需要类似[vue-next](https://github.com/vuejs/vue-next)，单独先领出来搞，而且现在vux的webpack也是3.x，我之前尝试过vue cli 3，还不错的，脚手架也需要升级
> 
> 你可以发邮件让他帮你开权限 [i@mao.li](mailto:i@mao.li)

不知道你联系的上作者么？我七月发了一封邮件，昨天又发了一封邮件，都没有回复 😞

2022-01-11 03:09 UTC, caozhong1996 commented
加我微信吧: justmilkplease