Dev uploader
airyland/vux pull request #3786
Opened 2021-07-28 13:48 UTC by eJayYoung

Please makes sure the items are checked before submitting your PR, thank you!

* [x] `Rebase` before creating a PR to keep commit history clear.
* [x] `Only One commit`
* [x] No `eslint` errors

2021-07-28 14:05 UTC, eJayYoung commented
Resolve #3680

2021-07-28 14:06 UTC, eJayYoung commented
#3680

2021-08-22 09:02 UTC, caozhong1996 commented on src/components/uploader/preview.vue
> +<template>
这个预览的组件可以使用vux自带的preview吗，感觉重复实现有些不好。

2021-08-22 09:22 UTC, caozhong1996 commented on src/components/uploader/index.vue
> +          :key="index"
这里不应该使用index作为key，会导致元素全部重新渲染。
![diff](https://user-images.githubusercontent.com/26522151/130349746-423f63c9-c0c5-4a70-8e89-683ff3a12468.gif)

2021-08-22 09:27 UTC, caozhong1996 requested changes
抱歉啊，前段时间太忙了，现在才有时间仔细看代码。

2021-08-25 02:45 UTC, eJayYoung commented on src/components/uploader/preview.vue
> +<template>
好的，之前没注意到vux有preview

2021-08-25 02:48 UTC, eJayYoung commented
> 抱歉啊，前段时间太忙了，现在才有时间仔细看代码。

没事，我也最近业务比较忙，晚上有空回去修改

2021-09-05 11:35 UTC, caozhong1996 commented
👍

2021-09-05 11:35 UTC, merged