toast use <transition>, remove transition attribute
airyland/vux pull request #867
Opened 2017-02-07 08:55 UTC by wg5945

Please makes sure the items are checked before submitting your PR, thank you!

* [ ] `Rebase` before creating a PR to keep commit history clear.
* [ ] `Only One commit`
* [ ] No `eslint` errors

2017-02-07 09:12 UTC, lichunqiang approved these changes

2017-02-07 13:43 UTC, airyland requested changes
use :name="transition"

2017-02-07 14:02 UTC, wg5945 commented
ok,fix tomorrow

2017-02-08 03:11 UTC, airyland approved these changes

2017-02-08 03:55 UTC, airyland commented
Already squash into source.

2017-02-08 03:55 UTC, closed without merging